[constants]
serialID = 'ffff:0035'
location = 'Manual_Lab'
brokerIP = 'mqtt.docker.local'

[input.scanner]
serial = "ffff_0035"
connection_point = ["0", "7", "1.0"]

[[mqtt_send]]
url = "mqtt.docker.local"
port = 1883
topic = "worker_scan/"

[sqlite3]
dataBaseName = 'WORKER'
filePath = 'data/workerData.db'

[factory]
name = "Manual Assembly"
