[constants]
serialID = 'ffff:0035'
location = 'Manual_Lab'
brokerIP = 'mqtt.docker.local'

[input.scanner]
serial = "ffff_0035"
connection_point = ["0", "1.3"]


[sqlite3]
dataBaseName = 'WORKER'
filePath = 'data/workerData.db'

[factory]
name = "Manual Assembly"
