version: "2"

services:
    worker-tracking-app:
        extends:
            file: worker_tracking/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - worker.tracking.docker.local
        restart: unless-stopped

networks:
    internal:
        name: Manual
        external: true